title: My first website!
author: Benedictus Alvian Sofjan
email: your-email@domain.com
description: This is the first website created by Benedictus Alvian Sofjan

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
